# macro_engine.py
# ---------------------------------
# 无双 · CWI 自动计算引擎（Python版）
# ---------------------------------

from tvDatafeed import TvDatafeed, Interval
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ===== 1. 连接 TradingView 数据源 =====
username = 'buptchenlu'
password = 'Chen1201@lu'
tv = TvDatafeed(username, password, chromedriver_path=None)   # 无需登录即可拉公开数据

# ===== 2. 定义指标符号（与TradingView一致） =====
symbols = {
    'SP500':    ('AMEX:SPY', Interval.in_weekly),
    'HYG':      ('AMEX:HYG', Interval.in_weekly),
    'LQD':      ('AMEX:LQD', Interval.in_weekly),
    'DBC':      ('AMEX:DBC', Interval.in_weekly),
    'OIL':      ('NYMEX:CL1!', Interval.in_weekly),
    'COPPER':   ('COMEX:HG1!', Interval.in_weekly),
    'DXY':      ('TVC:DXY', Interval.in_weekly),
    'US10Y':    ('TVC:US10Y', Interval.in_weekly),
    'US02Y':    ('TVC:US02Y', Interval.in_weekly)
}

# ===== 3. 下载数据 =====
data = {}
for name, (symbol, interval) in symbols.items():
    print(f"Downloading {name}...")
    df = tv.get_hist(symbol=symbol, exchange=None, interval=interval, n_bars=2000)
    data[name] = df['close']

# 统一时间索引
df_all = pd.concat(data, axis=1).dropna()

# ===== 4. 定义指标函数 =====
def yoy(series, n=52):
    return (series - series.shift(n)) / series.shift(n) * 100

def zscore(series, n=52):
    return (series - series.rolling(n).mean()) / series.rolling(n).std()

# ===== 5. 构建四大因子 =====
liq = zscore(yoy(df_all['HYG']/df_all['LQD']))
gr  = zscore(yoy(df_all['COPPER']/df_all['OIL']))
pr  = zscore(yoy(df_all['DBC']))
cd  = zscore(yoy((df_all['US10Y'] - df_all['US02Y']) - df_all['DXY']))

# ===== 6. 聚合权重 =====
w_liq, w_gr, w_pr, w_cd = 0.35, 0.25, 0.20, 0.20
cwi = (w_liq*liq + w_gr*gr + w_pr*pr + w_cd*cd) / (w_liq + w_gr + w_pr + w_cd)
cwi = cwi.dropna()

# ===== 7. 绘制结果 =====
plt.figure(figsize=(12,5))
plt.plot(cwi, color='red', linewidth=2, label='Crypto Weather Index (CWI)')
plt.axhline(0, color='gray', linestyle='--')
plt.title("CWI · Auto-Generated by WuShuang Macro Engine", fontsize=14)
plt.legend()
plt.grid(True)
plt.show()

# ===== 8. 保存结果 =====
cwi.to_csv('cwi_output.csv', header=['CWI'])
print("✅ Saved: cwi_output.csv")
